from django.db import models

class application(models.Model):
	fullName		 		= models.CharField(max_length=400,null=True)
	email			 		= models.CharField(max_length=400,null=True)
	uscId					= models.IntegerField(default=0,null=True)
	major			 		= models.CharField(max_length=400,null=True)
	minor			 		= models.CharField(max_length=400,null=True)
	gradYear				= models.IntegerField(default=0,null=True)
	available				= models.BooleanField(default=False)
	roles					= models.TextField(null=True)
	otherRole				= models.TextField(null=True)
	roleNotes				= models.TextField(null=True)
	desiredOutcome			= models.TextField(null=True)
	desiredOutcomeNotes		= models.TextField(null=True)
	contribution			= models.TextField(null=True)
	contributionNotes		= models.TextField(null=True)
	recentProj				= models.TextField(null=True)
	recentProjNotes			= models.TextField(null=True)
	dailyProb				= models.TextField(null=True)
	dailyProbNotes			= models.TextField(null=True)
	excitingTech			= models.TextField(null=True)
	excitingTechNotes		= models.TextField(null=True)
	devToolsSoft			= models.TextField(null=True)
	devToolsSoftNotes		= models.TextField(null=True)
	devToolsHard			= models.TextField(null=True)
	devToolsHardNotes		= models.TextField(null=True)
	designTools				= models.TextField(null=True)
	designToolsNotes		= models.TextField(null=True)
	otherTools				= models.TextField(null=True)
	otherToolsNotes			= models.TextField(null=True)
	resume					= models.URLField(null=True)
	resumeNotes				= models.TextField(null=True)
	portfolio				= models.URLField(null=True)
	portfolioNotes			= models.TextField(null=True)
	whatWork				= models.TextField(null=True)
	whatWorkNotes			= models.TextField(null=True)
	otherOrg				= models.TextField(null=True)
	otherOrgNotes			= models.TextField(null=True)
	referral				= models.TextField(null=True)
	joke					= models.TextField(null=True)
	annotated				= models.BooleanField(default=False)
	dedicationRating		= models.IntegerField(null=True)
	funRating				= models.IntegerField(null=True)
	experienceRating		= models.IntegerField(null=True)
	imaginationRating		= models.IntegerField(null=True)
	naughtyRating			= models.IntegerField(null=True)
	notes					= models.TextField(null=True)
	annotator				= models.CharField(max_length=100, null=True)
	final					= models.CharField(max_length=200, null=True)
