# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160601192924 on 2016-08-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('uscId', models.IntegerField(default=0)),
                ('major', models.CharField(max_length=400)),
                ('minor', models.CharField(max_length=400)),
                ('gradYear', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('roles', models.TextField()),
                ('otherRole', models.TextField()),
                ('roleNotes', models.TextField()),
                ('desiredOutcome', models.TextField()),
                ('desiredOutcomeNotes', models.TextField()),
                ('contribution', models.TextField()),
                ('contributionNotes', models.TextField()),
                ('recentProj', models.TextField()),
                ('recentProjNotes', models.TextField()),
                ('dailyProb', models.TextField()),
                ('dailyProbNotes', models.TextField()),
                ('excitingTech', models.TextField()),
                ('excitingTechNotes', models.TextField()),
                ('devToolsSoft', models.TextField()),
                ('devToolsSoftNotes', models.TextField()),
                ('devToolsHard', models.TextField()),
                ('devToolsHardNotes', models.TextField()),
                ('designTools', models.TextField()),
                ('designToolsNotes', models.TextField()),
                ('otherTools', models.TextField()),
                ('otherToolsNotes', models.TextField()),
                ('resume', models.URLField()),
                ('resumeNotes', models.TextField()),
                ('portfolio', models.URLField()),
                ('portfolioNotes', models.TextField()),
                ('whatWork', models.TextField()),
                ('whatWorkNotes', models.TextField()),
                ('otherOrg', models.TextField()),
                ('otherOrgNotes', models.TextField()),
                ('referral', models.TextField()),
                ('joke', models.TextField()),
            ],
        ),
    ]
