# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160601192924 on 2016-08-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='annotator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dedicationRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experienceRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='final',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='funRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='imaginationRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='naughtyRating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
