# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160601192924 on 2016-08-21 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0002_auto_20160821_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='funRating',
            new_name='resourcefulRating',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contributionNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dailyProbNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='designToolsNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='desiredOutcomeNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='devToolsHardNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='devToolsSoftNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='excitingTechNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='otherOrgNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='otherToolsNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='portfolioNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='recentProjNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resumeNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='roleNotes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='whatWorkNotes',
        ),
        migrations.AlterField(
            model_name='application',
            name='contribution',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dailyProb',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='designTools',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='desiredOutcome',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='devToolsHard',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='devToolsSoft',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='excitingTech',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='fullName',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gradYear',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='joke',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='major',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='minor',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='otherOrg',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='otherRole',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='otherTools',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='recentProj',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='referral',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='roles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='uscId',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='whatWork',
            field=models.TextField(null=True),
        ),
    ]
