# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160601192924 on 2016-08-23 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0003_auto_20160821_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='roles',
        ),
        migrations.AddField(
            model_name='application',
            name='designer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='developer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='product',
            field=models.BooleanField(default=False),
        ),
    ]
